# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'ORKSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ORKSample
  pod 'Zip', '~> 1.1'
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'

end
